// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrMkwGvTrSWyHOtFpMiZMMewqLD5XQ5c0',
    appId: '1:717483379177:android:345dcc9615e9251991e378',
    messagingSenderId: '717483379177',
    projectId: 'meal-monkey-38084',
    storageBucket: 'meal-monkey-38084.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW1aYVBRmZbDuWG7OuAFrDhmPWL6iCMQo',
    appId: '1:717483379177:ios:919f9136b90d8bde91e378',
    messagingSenderId: '717483379177',
    projectId: 'meal-monkey-38084',
    storageBucket: 'meal-monkey-38084.firebasestorage.app',
    androidClientId: '717483379177-39dl52v75d181vmhu70le4gm2k3e1o12.apps.googleusercontent.com',
    iosClientId: '717483379177-057drpignna0rdoi63o5rkmt5pjvapb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
